/**
 * Property-based tests for email validation logic.
 *
 * Feature: strandsmart-full-redesign
 * Properties 1 and 2 — email validation correctness
 */
import fc from "fast-check";
import { EMAIL_REGEX } from "utils/emailValidation";

// ---------------------------------------------------------------------------
// Property 1: Email validation rejects all non-email strings
// Validates: Requirements 2.1, 2.2
// ---------------------------------------------------------------------------
describe("Property 1: Email validation rejects all non-email strings", () => {
  it("should return false for any string that does not match the email pattern", () => {
    fc.assert(
      fc.property(
        fc.string().filter((s) => !EMAIL_REGEX.test(s)),
        (invalidEmail) => {
          // Assert that the regex correctly rejects the invalid email
          return EMAIL_REGEX.test(invalidEmail) === false;
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 2: Email validation error clears on valid input
// Validates: Requirements 2.3
// ---------------------------------------------------------------------------
describe("Property 2: Email validation error clears on valid input", () => {
  it("should return true for any valid email address generated by fc.emailAddress()", () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        (validEmail) => {
          // Assert that the regex correctly accepts the valid email
          return EMAIL_REGEX.test(validEmail) === true;
        }
      ),
      { numRuns: 100 }
    );
  });
});
